### PR TITLE
Added new programs

### PR DESCRIPTION
**Pull request by Anuragkar234**
## Description of new pull request

**Program Added** -  9
**Issue No.**- #6

## Checklist(self check):

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code
- [x] My Filename is in proper format
- [x] Proper commenting has been done

### CODE REVIEW

**Comment by Anuragkar234** [comment]
Can you add "hacktoberfest" label to the please, just a request though :)

**Comment by PrajjwalPathak** [comment]
> Can you add "hacktoberfest" label to the please, just a request though :)

It is already labelled.

**Comment by PrajjwalPathak** [comment]
> Can you add "hacktoberfest" label to the please, just a request though :)

It is already labeled.

**Comment by Anuragkar234** [comment]
> > Can you add "hacktoberfest" label to the please, just a request though :)
> 
> It is already labeled.

It's not there, i guess...atleast, you can keep for two-weeks, it would be really helpful

**Comment by PrajjwalPathak** [comment]
> > > Can you add "hacktoberfest" label to the please, just a request though :)
> > 
> > 
> > It is already labeled.
> 
> It's not there, i guess...atleast, you can keep for two-weeks, it would be really helpful

it's done.
But it is not compulsory for a repository to be labeled as hacktoberfest for creating a PR in hacktoberfest.

**Comment by Anuragkar234** [comment]
> > > > Can you add "hacktoberfest" label to the please, just a request though :)
> > > 
> > > 
> > > It is already labeled.
> > 
> > 
> > It's not there, i guess...atleast, you can keep for two-weeks, it would be really helpful
> 
> it's done.
> But it is not compulsory for a repository to be labeled as hacktoberfest for creating a PR in hacktoberfest.

But, when I logged in it showed as "ineligible repo", BTW, thanks :)

**Comment by PrajjwalPathak** [comment]
> > > > > Can you add "hacktoberfest" label to the please, just a request though :)
> > > > 
> > > > 
> > > > It is already labeled.
> > > 
> > > 
> > > It's not there, i guess...atleast, you can keep for two-weeks, it would be really helpful
> > 
> > 
> > it's done.
> > But it is not compulsory for a repository to be labeled as hacktoberfest for creating a PR in hacktoberfest.
> 
> But, when I logged in it showed as "ineligible repo", BTW, thanks :)

No problem

**Pull request merged**
